language: java
jdk:
- oraclejdk8
branchs:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_691c94e2ecbb_key -iv $encrypted_691c94e2ecbb_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
