language: java
jdk:
- oraclejdk8
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - 13.229.222.17 #受信主机，你的Linux服务器ip
before_install:
- openssl aes-256-cbc -K $encrypted_691c94e2ecbb_key -iv $encrypted_691c94e2ecbb_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh travis@13.229.222.17 -o StrictHostKeyChecking=no 'cd /workspace/lut-eureka && chmod 700 build.sh && ./build.sh '
